// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_9HCmCS8nUeSH1SfRu8dURBfK6xNZhIk',
    appId: '1:617358885530:web:7f4b87bdff0ac48c051523',
    messagingSenderId: '617358885530',
    projectId: 'auth-934ca',
    authDomain: 'auth-934ca.firebaseapp.com',
    storageBucket: 'auth-934ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRAt38_6NDNdJBciUdd4dNRZuoywAwwY',
    appId: '1:617358885530:android:bb3637fb105c3c2f051523',
    messagingSenderId: '617358885530',
    projectId: 'auth-934ca',
    storageBucket: 'auth-934ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc7-MS-zoD2yv9GcNpLeJRhYEGqa7cZdU',
    appId: '1:617358885530:ios:12b8578f3a448b2c051523',
    messagingSenderId: '617358885530',
    projectId: 'auth-934ca',
    storageBucket: 'auth-934ca.appspot.com',
    iosClientId: '617358885530-ojfps7ihtdo4bve476qh801hjbtq14de.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}
